//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databasefirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int oid { get; set; }
        public string oname { get; set; }
        public Nullable<System.DateTime> odate { get; set; }
        public string qty { get; set; }
        public Nullable<int> oprice { get; set; }
        public string ostatus { get; set; }
        public Nullable<int> custID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
